# This should take changes commited to master (merged) and kick off

name: hugo pages

on:
  push:
    branches:
        - master
    paths:
        - 'site/**'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - run: sudo npm install -g postcss-cli
      - run: sudo npm install autoprefixer

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2e89aa66d0093e4cd14751b3028fc1a179452c2e
        with:
          hugo-version: '0.70.0'
          extended: true #this is needed for Docsy theme

      # change dir and build
      - name: Build
        run: cd site && hugo 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
        with:
          cname: misfir3.org
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site/public 

