# This should take changes commited to master (merged) and kick off

name: hugo pages

on:
  push:
    branches:
        - master
    paths:
        - 'site/**'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - run: sudo npm install -g postcss-cli
      - run: sudo npm install autoprefixer

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@e2d599a0309d71c8131fb672b63ca3a578266c08
        with:
          hugo-version: '0.70.0'
          extended: true #this is needed for Docsy theme

      # change dir and build
      - name: Build
        run: cd site && hugo 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@1828d864aeb7ba79a37f40035aa6d0b7ff66254f
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site/public 

